import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./ApplicantDashboard.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Listing Data",
  description: "Generated by yours truly",
};

export default function ApplicantLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
